project:
  type: website
  # output-dir: docs
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Alphacar_"
  google-analytics: "G-YXVMSHZ5VF"
  sidebar:
    style: docked
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/alpha216/audio-quarto
    conetents:
      - text: Home
        href: index.qmd

format:
  html:
    theme: litera
    toc: true
